export const LANG_TO_ID = {
  "en":     [0,   "English (default / US)"],
  "en-US":  [0,   "English (United States)"],
  "en-GB":  [1,   "English (United Kingdom)"],
  "es-ES":  [2,   "Spanish (Spain)"],
  "es":     [3,   "Spanish (default / Latin America)"],
  "es-US":  [3,   "Spanish (US Latin American)"],
  "zh-CN":  [4,   "Chinese (Mandarin, Simplified)"],
  "hi":     [6,   "Hindi"],
  "hi-IN":  [6,   "Hindi (India)"],
  "ar":     [7,   "Arabic"],
  "ar-AR":  [7,   "Arabic"],
  "fr":     [8,   "French (default / France)"],
  "fr-FR":  [8,   "French (France)"],
  "de":     [9,   "German"],
  "de-DE":  [9,   "German (Germany)"],
  "ja":     [10,  "Japanese"],
  "ja-JP":  [10,  "Japanese"],
  "ru":     [11,  "Russian"],
  "ru-RU":  [11,  "Russian"],
  "pt-BR":  [12,  "Portuguese (Brazil)"],
  "pt":     [13,  "Portuguese (default / Portugal)"],
  "pt-PT":  [13,  "Portuguese (Portugal)"],
  "ko":     [14,  "Korean"],
  "ko-KR":  [14,  "Korean (South Korea)"],
  "it":     [15,  "Italian"],
  "it-IT":  [15,  "Italian"],
  "nl":     [16,  "Dutch"],
  "nl-NL":  [16,  "Dutch (Netherlands)"],
  "pl":     [17,  "Polish"],
  "pl-PL":  [17,  "Polish"],
  "tr":     [18,  "Turkish"],
  "tr-TR":  [18,  "Turkish"],
  "uk":     [19,  "Ukrainian"],
  "uk-UA":  [19,  "Ukrainian"],
  "ro":     [20,  "Romanian"],
  "ro-RO":  [20,  "Romanian"],
  "el":     [21,  "Greek"],
  "el-GR":  [21,  "Greek"],
  "cs":     [22,  "Czech"],
  "cs-CZ":  [22,  "Czech"],
  "hu":     [23,  "Hungarian"],
  "hu-HU":  [23,  "Hungarian"],
  "sv":     [24,  "Swedish"],
  "sv-SE":  [24,  "Swedish"],
  "da":     [25,  "Danish"],
  "da-DK":  [25,  "Danish"],
  "fi":     [26,  "Finnish"],
  "fi-FI":  [26,  "Finnish"],
  "sk":     [28,  "Slovak"],
  "sk-SK":  [28,  "Slovak"],
  "hr":     [29,  "Croatian"],
  "hr-HR":  [29,  "Croatian"],
  "bg":     [30,  "Bulgarian"],
  "bg-BG":  [30,  "Bulgarian"],
  "lt":     [31,  "Lithuanian"],
  "lt-LT":  [31,  "Lithuanian"],
  "th":     [32,  "Thai"],
  "th-TH":  [32,  "Thai"],
  "vi":     [33,  "Vietnamese"],
  "vi-VN":  [33,  "Vietnamese"],
  "et":     [60,  "Estonian"],
  "et-EE":  [60,  "Estonian"],
  "lv":     [61,  "Latvian"],
  "lv-LV":  [61,  "Latvian"],
  "sl":     [62,  "Slovenian"],
  "sl-SI":  [62,  "Slovenian"],
  "he":     [64,  "Hebrew"],
  "he-IL":  [64,  "Hebrew (Israel)"],
  "fr-CA":  [100, "French (Canada)"],
  "auto":   [101, "Auto-detect"],
  "mt":     [102, "Maltese"],
  "mt-MT":  [102, "Maltese"],
  "nb":     [103, "Norwegian Bokmål"],
  "nb-NO":  [103, "Norwegian Bokmål"],
  "nn":     [104, "Norwegian Nynorsk"],
  "nn-NO":  [104, "Norwegian Nynorsk"],
};

export function langName(code) {
  const entry = LANG_TO_ID[code];
  return entry ? entry[1] : null;
}

export function langId(code) {
  const entry = LANG_TO_ID[code];
  return entry ? entry[0] : null;
}
